[project]
name = "german-ai-flashcard-projekt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.124.4",
    "fastapi-cli>=0.0.16",
    "uvicorn>=0.38.0",
]
