[project]
name = "German_AI_Flashcard_Projekt"
version = "0.1.0"
description = "German AI Flashcard Project"
authors = [
    { name = "Jack Brown" }
]
dependencies = [
    "spacy==3.8.11",
    "fastapi==0.124.4",
    "uvicorn==0.38.0"
]

